# Generated by Django 3.1.4 on 2020-12-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='schedule',
            field=models.JSONField(default={'schedule_day': [{'end': 16, 'start': 8}]}),
        ),
    ]
