# Generated by Django 3.1.4 on 2020-12-26 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20201226_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='start_time',
            field=models.IntegerField(default=8, validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(16)]),
        ),
    ]
