# Generated by Django 3.1.4 on 2020-12-26 19:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20201226_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='start_time',
            field=models.IntegerField(default=8, validators=[django.core.validators.MaxValueValidator(16), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.barber')),
            ],
        ),
    ]
