# Generated by Django 3.1.4 on 2020-12-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20201226_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='service',
            field=models.CharField(choices=[('HAIR', 'HAIR_CUT'), ('WAX', 'WAX'), ('SHAVE', 'SHAVE')], default='HAIR', max_length=16),
        ),
    ]
