# Generated by Django 3.1.4 on 2020-12-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_client_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='service',
            field=models.CharField(choices=[('HAIR', 'HAIR CUT'), ('WAX', 'WAX'), ('SHAVE', 'SHAVE')], default='HAIR', max_length=16),
        ),
    ]
