# Generated by Django 3.1.4 on 2020-12-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20201226_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='start_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
