# Generated by Django 3.1.4 on 2021-01-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_client_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='barber_avatar'),
        ),
    ]
