# Generated by Django 3.1.4 on 2021-01-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_barber_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='barber_avatar'),
        ),
    ]
