# Generated by Django 3.1.4 on 2021-01-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20210105_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='schedule',
            field=models.TextField(default={'schedule_day': [{'end': 16, 'start': 8}]}),
        ),
    ]
