# Generated by Django 3.1.4 on 2021-01-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20210107_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='schedule',
            field=models.TextField(default='\n{\n    "schedule_day": [\n        {\n            "start": 8,\n            "end": 16\n        }\n    ]\n}\n'),
        ),
    ]
